<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net8.0-windows</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\VoxelSharp.Abstractions\VoxelSharp.Abstractions.csproj"/>
        <ProjectReference Include="..\VoxelSharp.Client\VoxelSharp.Client.csproj" />
        <ProjectReference Include="..\VoxelSharp.Core\VoxelSharp.Core.csproj"/>
        <ProjectReference Include="..\VoxelSharp.Modding\VoxelSharp.Modding.csproj"/>
        <ProjectReference Include="..\VoxelSharp.Renderer\VoxelSharp.Renderer.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="OpenTK" Version="4.9.4" />
    </ItemGroup>

    <Target Name="PostBuild" AfterTargets="Build">
        <PropertyGroup>
            <ModsDirectory>..\.mods</ModsDirectory>
            <ResourcesDirectory>$(ModsDirectory)\Resources</ResourcesDirectory>
        </PropertyGroup>

        <MakeDir Directories="$(ModsDirectory)" Condition="!Exists('$(ModsDirectory)')"/>

        <Copy SourceFiles="$(OutputPath)\$(AssemblyName).dll" DestinationFolder="$(ModsDirectory)"/>

        <Copy SourceFiles="$(OutputPath)\GLWpfControl.dll" DestinationFolder="$(ModsDirectory)" Condition="Exists('$(OutputPath)\GLWpfControl.dll')"/>

        <Exec Command="robocopy &quot;$(OutputPath)\Resources&quot; &quot;$(ResourcesDirectory)&quot; /E /COPY:DAT || exit 0" Condition="Exists('$(OutputPath)\Resources\')"/>
    </Target>
</Project>