<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0-windows</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <UseWPF>true</UseWPF>

        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\ImGUIMod\ImGUIMod.csproj" />
        <ProjectReference Include="..\VoxelSharp.Abstractions\VoxelSharp.Abstractions.csproj" />
        <ProjectReference Include="..\VoxelSharp.Client\VoxelSharp.Client.csproj" />
        <ProjectReference Include="..\VoxelSharp.Core\VoxelSharp.Core.csproj" />
        <ProjectReference Include="..\VoxelSharp.Modding\VoxelSharp.Modding.csproj" />
        <ProjectReference Include="..\VoxelSharp.Renderer\VoxelSharp.Renderer.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="ImGui.NET" Version="1.91.6.1" />
        <PackageReference Include="JetBrains.Annotations" Version="2025.2.4" />
        <PackageReference Include="OpenTK.GLWpfControl" Version="4.*" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Patches\" />
    </ItemGroup>

    <ItemGroup>
      <Page Update="WPF\Windows\RetroMessageBox.xaml">
        <Generator>MSBuild:Compile</Generator>
        <XamlRuntime>Wpf</XamlRuntime>
        <SubType>Designer</SubType>
      </Page>
    </ItemGroup>

    <ItemGroup>
        <Resource Include="WPF\Icons\icon.ico" />
        <None Remove="WPF\Icons\config.ico" />
        <Resource Include="WPF\Icons\config.ico" />
    </ItemGroup>

    <Target Name="PostBuild" AfterTargets="Build">
        <PropertyGroup>
            <ModsDirectory>..\.mods</ModsDirectory>
            <ResourcesDirectory>$(ModsDirectory)\Resources</ResourcesDirectory>
        </PropertyGroup>

        <MakeDir Directories="$(ModsDirectory)" Condition="!Exists('$(ModsDirectory)')"/>

        <Copy SourceFiles="$(OutputPath)\$(AssemblyName).dll" DestinationFolder="$(ModsDirectory)"/>

        <Copy SourceFiles="$(OutputPath)\GLWpfControl.dll" DestinationFolder="$(ModsDirectory)" Condition="Exists('$(OutputPath)\GLWpfControl.dll')"/>

        <Exec Command="robocopy &quot;$(OutputPath)\Resources&quot; &quot;$(ResourcesDirectory)&quot; /E /COPY:DAT || exit 0" Condition="Exists('$(OutputPath)\Resources\')"/>
    </Target>

</Project>