<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0-windows</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
        <Authors>Lukas Olson</Authors>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\VoxelSharp.Client\VoxelSharp.Client.csproj"/>
        <ProjectReference Include="..\VoxelSharp.Core\VoxelSharp.Core.csproj"/>
        <ProjectReference Include="..\VoxelSharp.Modding\VoxelSharp.Modding.csproj"/>
        <ProjectReference Include="..\VoxelSharp.Resources\VoxelSharp.Resources.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="HarmonyX" Version="2.13.0"/>
    </ItemGroup>

    <ItemGroup>
      <Compile Remove="Test.cs" />
    </ItemGroup>

    <ItemGroup>
      <None Update="Shaders\sky.frag">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Shaders\sky.vert">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Resources\Shaders\sky.frag">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Resources\Shaders\sky.vert">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Resources\" />
    </ItemGroup>


    <Target Name="PostBuild" AfterTargets="Build">
        <PropertyGroup>
            <ModsDirectory>..\.mods</ModsDirectory>
            <ResourcesDirectory>$(ModsDirectory)\Resources</ResourcesDirectory>
        </PropertyGroup>

        <MakeDir Directories="$(ModsDirectory)" Condition="!Exists('$(ModsDirectory)')"/>

        <!-- Remove the ResourcesDirectory if it exists -->
        <RemoveDir Directories="$(ResourcesDirectory)" Condition="Exists('$(ResourcesDirectory)')"/>

        <MakeDir Directories="$(ResourcesDirectory)"/>

        <Copy SourceFiles="$(OutputPath)\$(AssemblyName).dll" DestinationFolder="$(ModsDirectory)"/>

        <Exec Command="robocopy &quot;$(OutputPath)\Resources&quot; &quot;$(ResourcesDirectory)&quot; /E /COPY:DAT || exit 0" Condition="Exists('$(OutputPath)\Resources\')"/>
    </Target>


</Project>
